### ISSUE TITLE
GCLOUD_PROJECT is now GOOGLE_CLOUD_PROJECT

### ISSUE THREAD

**Issue by nikmartin** [tohagan/firebase-env#1]
Just implemented your awesome script, but when I ran it and then ran a script that uses the admin SDK, I got this error:
```
FirebaseAuthError: Failed to determine project ID for Auth. Initialize the SDK with service account credentials or set project ID as an app option. Alternatively set the GOOGLE_CLOUD_PROJECT environment variable.
    at FirebaseAuthError.FirebaseError [as constructor] (/admin-cli/node_modules/firebase-admin/lib/utils/error.js:42:28)
    at FirebaseAuthError.PrefixedFirebaseError [as constructor] (/admin-cli/node_modules/firebase-admin/lib/utils/error.js:88:28)
    at new FirebaseAuthError (/admin-cli/node_modules/firebase-admin/lib/utils/error.js:147:16)
    at /admin-cli/node_modules/firebase-admin/lib/auth/auth-api-request.js:128:23 {
  errorInfo: {
    code: 'auth/invalid-credential',
    message: 'Failed to determine project ID for Auth. Initialize the SDK with service account credentials or set project ID as an app option. Alternatively set the GOOGLE_CLOUD_PROJECT environment variable.'
  },
  codePrefix: 'auth'
}
```

**Comment by tohagan** [comment]
Thanks ... I found a reference to this change in 

- https://github.com/googleapis/cloud-profiler-nodejs/issues/152

**Comment by tohagan** [comment]
Fixed.
